[package]
name = "ezql-core"
version = "0.1.0"
edition = "2021"

[features]
default = []
sqlite = ["rusqlite"]

[dependencies]
rusqlite = { version = "0.26.0", optional = true, features = ["bundled"] }